routes/index.py
import os
import time
import uuid

import gevent
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app
)
from flask_sqlalchemy import SQLAlchemy

from werkzeug.datastructures import FileStorage

from models.base_model import db
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache
# from routes import current_user

import json

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():

    time.sleep(0.1)
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    User.register(form)

    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        log('index login key <{}> user_id <{}>'.format(key, u.id))
        cache.set(key, u.id)
        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response
        # session['user_id'] = u.id
        # return redirect(url_for('topic.index'))


def created_topic(user_id):
    topic = Topic.all(user_id=user_id)
    topic = sorted(topic, key=lambda m: m.created_time, reverse=True)
    return topic


def replied_topic(user_id):

    replied = Reply.all(user_id=user_id)
    replied = sorted(replied, key=lambda m: m.created_time, reverse=True)
    print('replied', replied)
    return replied


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        # 获取发布的 topic
        topic = created_topic(u.id)
        # 获取参与的 topic
        replied = replied_topic(u.id)

        return render_template(
            'profile.html',
            user=u,
            topic=topic,
            replied=replied,
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='{}'.format(filename))

        return redirect(url_for('.profile'))


@main.route('/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return

    return send_from_directory('images', filename)


@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template(
            'setting.html',
            user=u
        )


@main.route('/update_setting', methods=['POST'])
def update_setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        form = request.form
        bio = form['bio']
        username = form['username']
        User.update(u.id, bio=bio, username=username)
        print('bio', User.bio)
        print('username', User.username)
        return redirect(url_for('.setting'))


@main.route('/update_password', methods=['POST'])
def update_password():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        form = request.form
        print('form', form, u.password, form['old_pass'])
        old_pass = User.salted_password(form['old_pass'])
        if u.password == old_pass:
            print('right')
            new_pass = User.salted_password(form['new_pass'])
            User.update(u.id, password=new_pass)
            return redirect(url_for('.setting'))
        return redirect(url_for('.setting'))


@main.route('/about')
def about():
    return render_template('about.html')

routes/reset.py
import uuid

from flask import Blueprint, request, render_template

import config
from models.message import send_mail
from models.user import User
from utils import log

main = Blueprint('reset', __name__)

find = {}


@main.route('/')
def index():
    return render_template("reset/reset.html", message="请输入用户名")


@main.route("/send", methods=['POST'])
def send():
    form = request.form
    username = form['username']
    user = User.one(username=username)
    print('users', user)
    if user is not None:
        user_id = user.id
        print('userid', user_id)
        token = str(uuid.uuid4())
        find[token] = user_id
        subject = '密码找回'
        author = config.admin_mail
        to = user.emailtemp
        content = '请点击链接修改密码 https://www.auramux.com/reset/view?token={}'.format(token)
        send_mail(subject, author, to, content)
    else:
        return render_template("reset/reset.html", message="用户名错误")
    return render_template("reset/reset.html", message="重置邮件已发送，请注意查收")


@main.route('/view', methods=['GET'])
def view():
    token = request.args['token']
    if find[token] is not None:
        uid = find[token]
        u = User.one(id=uid)
        return render_template("reset/update.html", message="请输入新密码", uid=u.id, username=u.username)


@main.route('/update', methods=['POST'])
def update():
    uid = request.form['id']
    password = request.form['password']
    log('pass', password)
    log('user', User.one(id=uid))
    password = User.salted_password(password)
    log('password', password)
    User.update(uid, password=password)
    log(User.one(id=uid))
    return render_template("reset/update.html", message="密码重置成功")

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
        <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="manifest" href="/static/img/site.webmanifest">
</head>
<body>
<p >待完成</p>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>论坛主页</title>
    <link rel="stylesheet" href="/static/css/base.css">
    {#        <link rel="stylesheet" href="/static/css/style.css">#}
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="manifest" href="/static/img/site.webmanifest">
</head>
<body>
<div class="custom-padding">
    <nav>
        <div class="logo">Auramux</div>

        <ul class="menu-area">
            <li><a href="{{ url_for('.index') }}">话题</a></li>
            <li><a href="{{ url_for('index.setting') }}">设置</a></li>
            <li><a href="{{ url_for('index.profile') }}">个人中心</a></li>
            <li><a href="/">首页</a></li>
        </ul>
    </nav>
</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auramux</title>
    <link rel="stylesheet" href="/static/css/login.css">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="manifest" href="/static/img/site.webmanifest">
</head>
<body>
<div id="register-box">
    <div class="left-box">
        <h1> Sign up </h1>
        <form method="POST" action={{ url_for(".register") }}>
            <label>
                <input type="text" name="username" placeholder="Username"/>
            </label>
            <label>
                <input type="text" name="email" placeholder="Email"/>
            </label>
            <label>
                <input type="password" name="password" placeholder="Password"/>
            </label>
            <input type="submit" name="signup-Button" value="注册"/>
        </form>
    </div>
    <div class="right-box">
        <h1> Sign in </h1>
        <form method="POST" action={{ url_for(".login") }}>
            <label>
                <input type="text" name="username" placeholder="Username" value="test"/>
            </label>
            <label>
                <input type="password" name="password" placeholder="Password" value="test"/>
            </label>
            <input type="submit" name="sign-in-Button" value="登陆"/>
            <br><a href="{{ url_for('reset.index') }}" style="color:#ffffff;">Forget password？</a>
        </form>
    </div>
    <div class="Forget">
    </div>
    <div class="or">OR</div>
</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Form</title>
    <link rel="stylesheet" href="/static/css/login.css">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="manifest" href="/static/img/site.webmanifest">

</head>
<body>
<div id="register-box">
    <div class="left-box">
        <h1> Sign up </h1>
        <form method="POST" action={{ url_for(".add") }}>
            <label>
                <input type="text" name="username" placeholder="Username"/>
            </label>
            <label>
                <input type="text" name="email" placeholder="Email"/>
            </label>
            <label>
                <input type="password" name="password" placeholder="Password"/>
            </label>
            <input type="submit" name="signup-Button" value="注册"/>
        </form>
    </div>
    <div class="right-box">
        <h1> Sign in </h1>
        <form method="POST" action={{ url_for(".login") }}>
            <label>
                <input type="text" name="username" placeholder="Username" value="gua"/>
            </label>
            <label>
                <input type="text" name="password" placeholder="Password" value="123"/>
            </label>
            <input type="submit" name="signin-Button" value="登陆"/>
            <a href="reset/reset.html" style="color:#ffffff;">Forget password？</a>
        </form>
    </div>
    <div class="Forget">
    </div>
    <div class="or">OR</div>
</div>

</body>
</html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}个人主页{% endblock %}
{% block main %}
        <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src={{ user.image }} title="{{ user.username }}" alt="Smiley face">
                </div>
                <a class="dark">{{ user.username }}</a>

                <div class="user_profile">
                    <ul class="unstyled">
                        <li>
                            <i class="github"></i>
                            <a class="dark" target="_blank">
                                @{{ user.username }}
                            </a>
                        </li>


                    </ul>
                </div>
                <p class="col_fade">注册时间 {{ user.created_time | format_time }}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>

            <div class="inner">
                {% for t in topic %}
                    {# for i, r in enumerate(topic.replies())  #}
                    {% set u = t.user() %}
                    <div class='all topic'>
                        <a class="dark" href="/topic/{{ t.id }}" target="_blank">
                            {{ t.title }}</a>
                    </div>
                {% endfor %}
            </div>

        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>

            <div class="inner">
                {% for t in replied %}
                    {# for i, r in enumerate(topic.replies())  #}
                    {#% set u = t.user() %#}
                    <div class='all topics'>
                        <a class="dark" href="/topic/{{ t.topic_id }}" target="_blank">
                            {{ t.content }}</a>
                    </div>
                {% endfor %}
            </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">上传头像</span>
            </div>
            <div class="inner">
            <form method="post"
                  action="{{ url_for('.avatar_add') }}"
                  enctype="multipart/form-data"
            >
                <input type="file" name="avatar">
                <button class="editor_buttons" type="submit">上传头像</button>
            </form>
            </div>
        </div>
        </div>
    </div>
    <script>
    (function () {
        var editor = new Editor();
        editor.render($('.editor')[0]);
    })();

</script>
{% endblock %}
{#</div>#}


{#{% endblock %}#}


<!--</body>-->
<!--</html>-->

templates/setting.html
<link href="/static/css/user.css" media="all" rel="stylesheet">
{% extends "topic/base.html" %}

{% block title %}设置{% endblock %}
{% block main %}
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">


                <form id="setting_form" class="form-horizontal" action="{{ url_for('.update_setting') }}" method="post"
                      _lpchecked="1">
                    <div class="control-group">
                        <label class="control-label" for="username">用户名</label>

                        <div class="controls">
                            <input class="input-xlarge readonly" id="username" name="username" size="30" type="text"
                                   value="{{ user.username }}">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="email">电子邮件</label>

                        <div class="controls">
                            <input class="input-xlarge readonly" id="email" name="email" size="30" type="text"
                                   readonly="true" value="{{ user.email }}">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="bio">个性签名</label>

                        <div class="controls">
                            <textarea class="input-xlarge" id="bio" name="bio" size="30"></textarea>
                        </div>
                    </div>

                    <div class="form-actions">
                        <input type="submit" class="editor_buttons" data-loading-text="保存中.." value="保存设置">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">更改密码</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.update_password') }}"
                      method="post">
                    <div class="control-group">
                        <label class="control-label" for="old_pass">当前密码</label>

                        <div class="controls">
                            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="new_pass">新密码</label>

                        <div class="controls">
                            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="editor_buttons" data-loading-text="更改中.." value="更改密码">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">上传头像</span>
            </div>
            <div class="inner">
                <form id="update" class="form-horizontal" method="post"
                  action="{{ url_for('.avatar_add') }}" enctype="multipart/form-data">
                    <div class="control-group">
                        <label class="control-label" for="old_pass"></label>
                        <input type="file" name="avatar">
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="editor_buttons" data-loading-text="上传中.." value="上传头像">
                    </div>
                </form>
            </div>
        </div>


    </div>
{% endblock %}
{#</div>#}

<script>
    (function () {
        var editor = new Editor();
        editor.render($('.editor')[0]);
    })();

</script>

{#{% endblock %}#}


<!--</body>-->
<!--</html>-->