models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
import os
import time
import uuid

import gevent
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app
)
from flask_sqlalchemy import SQLAlchemy

from werkzeug.datastructures import FileStorage

from models.base_model import db
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache
# from routes import current_user

import json

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():

    time.sleep(0.1)
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    User.register(form)

    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        log('index login key <{}> user_id <{}>'.format(key, u.id))
        cache.set(key, u.id)
        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response
        # session['user_id'] = u.id
        # return redirect(url_for('topic.index'))


def created_topic(user_id):
    topic = Topic.all(user_id=user_id)
    topic = sorted(topic, key=lambda m: m.created_time, reverse=True)
    return topic


def replied_topic(user_id):

    replied = Reply.all(user_id=user_id)
    replied = sorted(replied, key=lambda m: m.created_time, reverse=True)
    print('replied', replied)
    return replied


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        # 获取发布的 topic
        topic = created_topic(u.id)
        # 获取参与的 topic
        replied = replied_topic(u.id)

        return render_template(
            'profile.html',
            user=u,
            topic=topic,
            replied=replied,
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='{}'.format(filename))

        return redirect(url_for('.profile'))


@main.route('/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return

    return send_from_directory('images', filename)


@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template(
            'setting.html',
            user=u
        )


@main.route('/update_setting', methods=['POST'])
def update_setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        form = request.form
        bio = form['bio']
        username = form['username']
        User.update(u.id, bio=bio, username=username)
        print('bio', User.bio)
        print('username', User.username)
        return redirect(url_for('.setting'))


@main.route('/update_password', methods=['POST'])
def update_password():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        form = request.form
        print('form', form, u.password, form['old_pass'])
        old_pass = User.salted_password(form['old_pass'])
        if u.password == old_pass:
            print('right')
            new_pass = User.salted_password(form['new_pass'])
            User.update(u.id, password=new_pass)
            return redirect(url_for('.setting'))
        return redirect(url_for('.setting'))


@main.route('/about')
def about():
    return render_template('about.html')

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    Request)

from models.message import Messages
from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, reply_link, reply_content):
    print('send_mail', sender, receivers, reply_content)
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        title = '你被 {} AT 了'.format(sender.username)
        Messages.send(
            title=title,
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, request.referrer, content)

    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    u = current_user()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    u = current_user()
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    u = current_user()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id, user=u)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {#    <link rel="stylesheet" href="/static/css/bootstrap.min.css">#}
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link href="/static/css/user.bak.css" media="all" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
    <link rel="manifest" href="/static/img/site.webmanifest">
    <head>
<body>

<!-- slide bar -->
<div class="custom-padding">
    <nav>
        <div class="logo">Auramux</div>

        <ul class="menu-area">
            <li><a href="{{ url_for('topic.index') }}">首页</a></li>
            <li><a href="{{ url_for('index.setting') }}">设置</a></li>
            <li><a href="{{ url_for('index.profile') }}">个人中心</a></li>
            <li><a href="/">登陆</a></li>
        </ul>
    </nav>
</div>
<div id="main">

    <div id="sidebar">

        <div class="panel">

            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar">
                            <img src="/{{ user.image }} " alt="Smiley face">
                        </a>
                        <p>
                            <span class="user_name"><a class="dark"
                                                       href="{{ url_for("index.profile") }}">{{ user.username }} </a></span>

                        </p>

                        <div class="board clearfix">
                            <div class="floor">
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
        “{{ user.bio }}”
    </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="pub">
            <div class="inner">
                <a href="/topic/new?board_id=-1" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>

    </div>
    {% block main %}
    {% endblock %}
</div>
<div class="site-footer">
        <div class="copyright">Made by Auramux
        </div>
        <div class="copyright">蒙ICP备19003812号-1</div>
</div>

</body>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}{{ topic.title }}{% endblock %}
{% block main %}

    <div id="content">
    <div class='panel'>
        <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
            <div class="changes">
            <span>
                发布于 2 天前
            </span>
                <span>
                {% set u = topic.user() %}
                作者 {{ u.username }}
        	</span>
                <span>
          	    {{ topic.views }} 次浏览
        	</span>
                <span>
                来自 问答
            </span>
            </div>
        </div>

        <div class='inner topic'>
            <div class='topic_content'>
                <div class="markdown-text">{{ topic.content }}</div>
            </div>
        </div>
    </div>
    <div class='panel'>
        <div class="header">"回复主题"</div>
        <div class="cell reply_area reply_item">
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <label>
                    <textarea name="content" style="margin: 0px 0px 10px; width: 100%; height: 85px;"></textarea>
                </label>
                <button class="editor_buttons">添加回复</button>
            </form>
        </div>
    </div>
    <div class='panel'>
    <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
    </div>
    {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ u.username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 / {{ loop.length }}楼 •
                        <span>{{ r.created_time }}</span>
                    </a>
                </div>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">{{ r.content }}</div>

            </div>
        </div>
    {% endfor %}




    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="/static/js/marked.min.js"></script>
    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            // markdown -> html 的处理放在高亮前面
            // 因为高亮是针对 html 格式的
            // lang -> language 不需要转 prism 自动转了
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            // 自动加载对应的语言 不然要手动加入各个语言的 js
            Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
        }

        var __main = function () {
            markContents()
            highlight()
        }

        __main()

    </script>

{% endblock %}
</div>
</div>

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock %}
{% block main %}
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                    <a href="/topic?board_id={{ b.id }}"
                       class="topic-tab current-tab">
                        {{ b.title }}
                    </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
                                <a class="topic_title_delete"
                                   href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                    删除
                                </a>
                                <span class="topic_title_detail" style="text-align: right;">回复:{{ t.replies() | count }} / 阅读:{{ t.views }}</span>
                                <!--<a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">-->


                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{#</div>#}
<script>
    (function () {
        var editor = new Editor();
        editor.render($('.editor')[0]);
    })();

</script>

{#{% endblock %}#}


<!--</body>-->
<!--</html>-->

templates/topic/new.html
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
{% extends "topic/base.html" %}

{% block title %}发布新内容{% endblock %}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                        <!--<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">-->
                        <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="请输入标题"></textarea>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                    <textarea class='editor' name='content' rows='20'
                                              placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='editor_buttons' data-loading-text="提交中" value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();

    </script>

{% endblock %}

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>